#!/usr/bin/env bash
# EXPERIMENTAL milestone-3 driver: build R on Windows via src/gnuwin32
# using zig cc (x86_64-windows-gnu) for C/C++ and conda-forge MinGW
# gfortran for Fortran. The zig+gfortran ABI mix is validated (see
# TODO.md); wiring gnuwin32's Rtools assumptions to the pixi env is
# work in progress — expect this to fail partway and be iterated on.
. "$(dirname "$0")/env.sh"

if [ "$OS" != windows ]; then
  echo "error: this script is the Windows (gnuwin32) path — use 'pixi run build' elsewhere" >&2
  exit 1
fi

GNUWIN="$SRC_DIR/src/gnuwin32"
test -d "$GNUWIN" || { echo "error: R source not fetched — run 'pixi run fetch'" >&2; exit 1; }

# gnuwin32 invokes the toolchain as $(BINPREF)gcc / g++ / gfortran, so
# provide gcc/g++ command names that dispatch to the zig shims, plus
# unprefixed names for the binutils that ship prefixed in conda's
# MinGW gcc stack (windres for .rc resources, etc).
WINBIN="$BUILD_DIR/win-toolchain"
mkdir -p "$WINBIN"
cp "$TOOLCHAIN/zig-cc" "$WINBIN/gcc"
cp "$TOOLCHAIN/zig-cxx" "$WINBIN/g++"
chmod +x "$WINBIN/gcc" "$WINBIN/g++"
for tool in ar ranlib nm dlltool strip as ld; do
  src="$(command -v "x86_64-w64-mingw32-$tool" 2>/dev/null || true)"
  [ -n "$src" ] && [ ! -f "$WINBIN/$tool.exe" ] && cp "$src" "$WINBIN/$tool.exe"
done
# windres spawns its preprocessor via CreateProcess, which cannot run the
# bash-script gcc shim — point it at the native MinGW gcc for -E only.
REAL_WINDRES="$(command -v x86_64-w64-mingw32-windres)"
REAL_GCC="$(command -v x86_64-w64-mingw32-gcc)"
rm -f "$WINBIN/windres.exe"
cat > "$WINBIN/windres" << EOF
#!/usr/bin/env bash
exec "$REAL_WINDRES" --preprocessor="$REAL_GCC" \\
  --preprocessor-arg=-E --preprocessor-arg=-xc --preprocessor-arg=-DRC_INVOKED "\$@"
EOF
chmod +x "$WINBIN/windres"
export PATH="$WINBIN:$PATH"

cd "$GNUWIN"
# LOCAL_SOFT replaces Rtools' bundled headers/libs with the pixi env's
# conda-forge Library tree (mixed-style path so both make and zig cope).
LOCAL_SOFT="$(cygpath -m "$CONDA_PREFIX")/Library"
cat > MkRules.local << EOF
# Generated by scripts/build-gnuwin32.sh — pixi/zig toolchain (regenerated
# every run; do not edit)
BINPREF =
LOCAL_SOFT = $LOCAL_SOFT
# conda-forge tcl/tk on Windows uses the threaded '86t' library suffix
TCL_HOME = $LOCAL_SOFT
TCL_VERSION = 86t
# cairo graphics from conda-forge's cairo DLL (transitive deps resolve
# at runtime, so the link set is just cairo itself)
USE_CAIRO = YES
CAIRO_CPPFLAGS = -I$LOCAL_SOFT/include/cairo -I$LOCAL_SOFT/include/freetype2
CAIRO_LIBS = -lcairo -lfontconfig
EOF

# TCL_* are baked into etc/x64/Makeconf from the fixed/ template, not
# MkRules — patch template (pre-build) and generated copy (rebuilds).
for mkc in "$GNUWIN/fixed/etc/Makeconf" "$SRC_DIR/etc/x64/Makeconf"; do
  if [ -f "$mkc" ]; then
    sed -i 's|^TCL_VERSION *=.*|TCL_VERSION = 86t|' "$mkc"
    sed -i "s|^TCL_HOME *=.*|TCL_HOME = $LOCAL_SOFT|" "$mkc"
    # zig has no OpenMP runtime; unix configure detects this and leaves
    # these empty — make Windows package builds consistent (data.table
    # etc. fall back to single-threaded, same as linux/macOS slim)
    sed -i -E 's|^(SHLIB_OPENMP_[A-Z]+FLAGS) *=.*|\1 =|' "$mkc"
  fi
done

# Must be msys make (m2-make): gnuwin32 recipes need sh, and only an
# msys make can spawn the extensionless zig shim scripts.
MSYS_MAKE="$(command -v /usr/bin/make || command -v make)"
echo "== using make: $MSYS_MAKE"
LOG="$BUILD_DIR/gnuwin32-make.log"
echo "== gnuwin32 make all (experimental) — full log: $LOG"
rc=0
"$MSYS_MAKE" all > "$LOG" 2>&1 || rc=$?
# cairo devices are not part of 'all' even with USE_CAIRO=YES
if [ $rc -eq 0 ]; then
  "$MSYS_MAKE" cairodevices >> "$LOG" 2>&1 || rc=$?
fi
tail -30 "$LOG"
exit $rc
