#!/usr/bin/env bash
# EXPERIMENTAL milestone-3 driver: build R on Windows via src/gnuwin32
# using zig cc (x86_64-windows-gnu) for C/C++ and conda-forge MinGW
# gfortran for Fortran. The zig+gfortran ABI mix is validated (see
# TODO.md); wiring gnuwin32's Rtools assumptions to the pixi env is
# work in progress — expect this to fail partway and be iterated on.
. "$(dirname "$0")/env.sh"

if [ "$OS" != windows ]; then
  echo "error: this script is the Windows (gnuwin32) path — use 'pixi run build' elsewhere" >&2
  exit 1
fi

GNUWIN="$SRC_DIR/src/gnuwin32"
test -d "$GNUWIN" || { echo "error: R source not fetched — run 'pixi run fetch'" >&2; exit 1; }

# gnuwin32 invokes the toolchain as $(BINPREF)gcc / g++ / gfortran, so
# provide gcc/g++ command names that dispatch to the zig shims.
WINBIN="$BUILD_DIR/win-toolchain"
mkdir -p "$WINBIN"
cp "$TOOLCHAIN/zig-cc" "$WINBIN/gcc"
cp "$TOOLCHAIN/zig-cxx" "$WINBIN/g++"
chmod +x "$WINBIN/gcc" "$WINBIN/g++"
export PATH="$WINBIN:$PATH"

cd "$GNUWIN"
if [ ! -f MkRules.local ]; then
  cat > MkRules.local << EOF
# Generated by scripts/build-gnuwin32.sh — pixi/zig toolchain
BINPREF =
EOF
fi

# Must be msys make (m2-make): gnuwin32 recipes need sh, and only an
# msys make can spawn the extensionless zig shim scripts.
MSYS_MAKE="$(command -v /usr/bin/make || command -v make)"
echo "== using make: $MSYS_MAKE"
echo "== gnuwin32 make all (experimental) — log tail follows"
"$MSYS_MAKE" all 2>&1 | tail -40
